lib/ircois_web/router.ex
defmodule IrcoisWeb.Router do
  use IrcoisWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {IrcoisWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IrcoisWeb do
    pipe_through :browser
    get "/user/:user", UserController, :user
    live "/", PageLive, :index
    live "/grep", SearchLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", IrcoisWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: IrcoisWeb.Telemetry
    end
  end
end

lib/ircois_web/controllers/error_html.ex
defmodule IrcoisWeb.ErrorHTML do
  @moduledoc """
  This module is invoked by your endpoint in case of errors on HTML requests.

  See config/config.exs.
  """
  use IrcoisWeb, :html

  # If you want to customize your error pages,
  # uncomment the embed_templates/1 call below
  # and add pages to the error directory:
  #
  #   * lib/Ircois_web/controllers/error_html/404.html.heex
  #   * lib/Ircois_web/controllers/error_html/500.html.heex
  #
  # embed_templates "error_html/*"

  # The default is to render a plain text page based on
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def render(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/ircois_web/controllers/user_controller.ex
defmodule IrcoisWeb.UserController do
  use IrcoisWeb, :controller

  def user(conn, %{"user" => username}) do
    cfg = Ircois.Config.read_config()
    default_channel = hd(cfg.channels)

    data = %{nickname: username}
    # Activity per hour.
    buckets = Ircois.Statistics.active_hours(username, default_channel)
    most_active_start = buckets |> Map.to_list() |> Enum.sort_by(&elem(&1, 1), :desc) |> hd |> elem(0)
    most_active = {most_active_start, Time.add(most_active_start, 3600)}
    data = Map.put(data, :activity_buckets, buckets)
    data = Map.put(data, :most_active, most_active)

    # Total messages
    total = Ircois.Statistics.total_messages(username, default_channel)
    data = Map.put(data, :total, total)

    # Averag per day
    day_avg = Ircois.Statistics.avg_per_day(username, default_channel)
    data = Map.put(data, :avg_per_day, day_avg)

    # Karma
    karma = Ircois.Data.get_karma(username)
    data = Map.put(data, :karma, karma)

    # Last seen
    last_seen = Ircois.Data.last_seen(default_channel, username)

    data =
      case last_seen do
        nil ->
          Map.put(data, :last_seen, nil)

        _ ->
          Map.put(data, :last_seen, last_seen.when)
      end

    # First seen
    first_seen = Ircois.Data.first_seen(default_channel, username)

    data =
      case first_seen do
        nil ->
          Map.put(data, :first_seen, nil)

        _ ->
          Map.put(data, :first_seen, first_seen.when)
      end

    render(conn, "index.html", data: data)
  end
end

lib/ircois_web/controllers/user_html.ex
defmodule IrcoisWeb.UserHTML do
  @moduledoc """
  This module contains pages rendered by PageController.

  See the `page_html` directory for all templates available.
  """
  use IrcoisWeb, :html

  embed_templates "user_html/*"

  def bucket_values(buckets) do
    vals =
      buckets
      |> Enum.map_join(", ", fn {_t, p} ->
        "\"#{format_float(p * 100, 2)}\""
      end)

    "[#{vals}]"
  end

  def bucket_labels(buckets) do
    vals =
      buckets
      |> Enum.map_join(", ", fn {t, _p} ->
        hour = "#{t.hour}" |> String.pad_leading(2, "0")
        mins = "#{t.minute}" |> String.pad_leading(2, "0")
        "\"#{hour <> ":" <> mins}\""
      end)

    "[#{vals}]"
  end

  def format_datetime(nil), do: ""

  def format_datetime(dt) do
    Timex.format!(dt, "%d/%m/%Y %H:%M", :strftime)
  end

  def format_time(t) do
    hour = "#{t.hour}" |> String.pad_leading(2, "0")
    mins = "#{t.minute}" |> String.pad_leading(2, "0")
    hour <> ":" <> mins
  end

  def format_float(f, decimals \\ 2) do
    trunc(f * :math.pow(10, decimals)) / :math.pow(10, decimals)
  end
end

lib/ircois_web/live/page_live.ex
defmodule IrcoisWeb.PageLive do
  use IrcoisWeb, :live_view
  require Logger
  alias Ircois.PubSub

  @impl true
  def mount(_params, _session, socket) do
    Logger.debug("Socket mounted #{inspect(socket, pretty: true)} #{inspect(self())}")
    cfg = Ircois.Config.read_config()

    default_channel = hd(cfg.channels)

    # Subscribe to updates from the channel.
    PubSub.subscribe()

    # Loaded plugins
    plugins =
      Ircois.Plugin.Manager.registered_plugins()
      |> Enum.map(&Atom.to_string/1)
      |> Enum.map(&String.split(&1, "."))
      |> Enum.map(&List.last/1)

    # Most active users.
    users = Ircois.Data.most_active(default_channel)
    socket = assign(socket, :most_active, users)

    socket = assign(socket, :plugins, plugins)
    # Last n messages
    messages = Ircois.Data.get_last_n(default_channel, 10) |> Enum.reverse()
    color_map = nick_color_map(messages)
    socket = assign(socket, :messages, messages)
    socket = assign(socket, :color_map, color_map)

    # Karma top 10
    karma_top_10 = Ircois.Data.karma_top(10)
    socket = assign(socket, :karma_top_10, karma_top_10)

    # Karma bottom 10
    karma_bottom_10 = Ircois.Data.karma_bottom(10)
    socket = assign(socket, :karma_bottom_10, karma_bottom_10)

    # URLS
    urls = Ircois.Data.last_n_urls(10)
    socket = assign(socket, :urls, urls)

    # Activity
    day_totals = Ircois.Data.message_count_per_day(default_channel)
    hour_totals = Ircois.Data.message_count_per_hour(default_channel)
    socket = assign(socket, :day_totals, day_totals)
    socket = assign(socket, :hour_totals, hour_totals)

    socket = assign(socket, :channel, default_channel)
    {:ok, socket}
  end

  @impl true
  def handle_info({:new_message, message}, socket) do
    # Generate color map if the current user is not in there yet.
    color_map =
      socket.assigns.color_map
      |> Map.put_new(message.from, random_color())

    socket = assign(socket, :color_map, color_map)

    # Only keep the last n messages.
    messages = (socket.assigns.messages ++ [message]) |> Enum.take(-10)
    socket = assign(socket, :messages, messages)

    {:noreply, socket}
  end

  def handle_info({:new_karma, _karma}, socket) do
    # Top 10 Karma
    karma_top_10 = Ircois.Data.karma_top(10)
    socket = assign(socket, :karma_top_10, karma_top_10)

    karma_bottom_10 = Ircois.Data.karma_bottom(10)
    socket = assign(socket, :karma_bottom_10, karma_bottom_10)
    {:noreply, socket}
  end

  def handle_info({:new_url, _karma}, socket) do
    # URLS
    urls = Ircois.Data.last_n_urls(12)
    socket = assign(socket, :urls, urls)
    {:noreply, socket}
  end

  def handle_info(_m, socket) do
    {:noreply, socket}
  end

  defp show_time(datetime) do
    datetime
    |> DateTime.to_time()
    |> Time.to_string()
  end

  def hour_totals_labels(hourtotals) do
    hourtotals
    |> Enum.map(fn %{hour: hour} ->
      hour
    end)
    |> Enum.map(&labels_hour/1)
    |> Jason.encode!()
  end

  def hour_totals_values(hourtotals) do
    hourtotals
    |> Enum.map(fn %{total: t} ->
      t
    end)
    |> Jason.encode!()
  end

  def day_totals_labels(daytotals) do
    daytotals
    |> Enum.map(fn %{day: day} ->
      day
    end)
    |> Enum.map(&labels_day/1)
    |> Jason.encode!()
  end

  def day_totals_values(daytotals) do
    daytotals
    |> Enum.map(fn %{total: t} ->
      t
    end)
    |> Jason.encode!()
  end

  def labels_day(dt) do
    day = "#{dt.day}"
    month = "#{dt.month}" |> String.pad_leading(2, "0")
    "#{day}/#{month}"
  end

  def labels_hour(dt) do
    day = "#{dt.day}"
    month = "#{dt.month}" |> String.pad_leading(2, "0")
    hour = "#{dt.hour}" |> String.pad_leading(2, "0")
    minute = "#{dt.minute}" |> String.pad_leading(2, "0")
    "#{day}/#{month} #{hour}:#{minute}"
  end

  defp nick_color_map(messages) do
    messages
    |> Enum.map(fn m -> m.from end)
    |> Enum.uniq()
    |> Enum.map(fn n ->
      {n, random_color()}
    end)
    |> Enum.into(%{})
  end

  defp random_color do
    :rand.uniform(16_777_215) |> Integer.to_string(16)
  end
end

lib/ircois_web/live/search_live.ex
defmodule IrcoisWeb.SearchLive do
  use IrcoisWeb, :live_view
  require Logger
  alias Ircois.PubSub

  def mount(_params, _session, socket) do
    Logger.debug("Socket mounted #{inspect(socket, pretty: true)} #{inspect(self())}")
    PubSub.subscribe()
    socket = assign(socket, :messages, [])
    {:ok, socket}
  end

  def handle_event("search", %{"query" => query}, socket) do
    cfg = Ircois.Config.read_config()
    channel = hd(cfg.channels)
    # Sanitize input.

    # Ignore empty queries.
    case String.trim(query) do
      "" ->
        {:noreply, socket}

      _ ->
        from = Regex.named_captures(~r/from:(?<from>(\w+))?/i, query)

        matches =
          if from == nil or from["from"] == "" do
            Ircois.Data.grep(query, channel)
          else
            query = Regex.replace(~r/from:(?<from>(\w+))?/i, query, "") |> String.trim()
            Ircois.Data.grep(query, channel, from["from"])
          end

        color_map = nick_color_map(matches)

        socket = assign(socket, :messages, matches)
        socket = assign(socket, :color_map, color_map)

        {:noreply, socket}
    end
  end

  def handle_info(_m, socket) do
    {:noreply, socket}
  end

  defp show_time(dt) do
    Timex.format!(dt, "%d/%m/%Y %H:%M", :strftime)
  end

  def labels_day(dt) do
    day = "#{dt.day}"
    month = "#{dt.month}" |> String.pad_leading(2, "0")
    "#{day}/#{month}"
  end

  def labels_hour(dt) do
    day = "#{dt.day}"
    month = "#{dt.month}" |> String.pad_leading(2, "0")
    hour = "#{dt.hour}" |> String.pad_leading(2, "0")
    minute = "#{dt.minute}" |> String.pad_leading(2, "0")
    "#{day}/#{month} #{hour}:#{minute}"
  end

  defp nick_color_map(messages) do
    messages
    |> Enum.map(fn m -> m.from end)
    |> Enum.uniq()
    |> Enum.map(fn n ->
      {n, random_color()}
    end)
    |> Enum.into(%{})
  end

  defp random_color do
    :rand.uniform(16_777_215) |> Integer.to_string(16)
  end
end

lib/ircois_web/views/user_view.ex
defmodule IrcoisWeb.UserView do
  use IrcoisWeb, :view

  def bucket_values(buckets) do
    vals =
      buckets
      |> Enum.map(fn {_t, p} ->
        "\"#{format_float(p * 100, 2)}\""
      end)
      |> Enum.join(", ")

    "[#{vals}]"
  end

  def bucket_labels(buckets) do
    vals =
      buckets
      |> Enum.map(fn {t, _p} ->
        hour = "#{t.hour}" |> String.pad_leading(2, "0")
        mins = "#{t.minute}" |> String.pad_leading(2, "0")
        "\"#{hour <> ":" <> mins}\""
      end)
      |> Enum.join(", ")

    "[#{vals}]"
  end

  def format_datetime(nil), do: ""

  def format_datetime(dt) do
    Timex.format!(dt, "%d/%m/%Y %H:%M", :strftime)
  end

  def format_time(t) do
    hour = "#{t.hour}" |> String.pad_leading(2, "0")
    mins = "#{t.minute}" |> String.pad_leading(2, "0")
    hour <> ":" <> mins
  end

  def format_float(f, decimals \\ 2) do
    trunc(f * :math.pow(10, decimals)) / :math.pow(10, decimals)
  end
end

lib/ircois_web/live/page_live.html.leex
<span id="daytotals" data-labels='<%= raw(@day_totals |> day_totals_labels()) %>' data-values='<%= raw(@day_totals |> day_totals_values()) %>'></span>
<span id="hourtotals" data-labels='<%= raw(@hour_totals |> hour_totals_labels()) %>' data-values='<%= raw(@hour_totals |> hour_totals_values()) %>'></span>

<!-- Plugins -->
<div class="row">
    <div class="col-lg-12">
        <div class="widget">
            <%= for p <- @plugins do  %>
                <span class="badge bg-success"><%= p %></span>
            <% end %>
        </div>
    </div>
</div>


<!-- chatbox -->
<div class="row">
	<div class="col-lg-12">
		<div class="widget">
			<table class="table chatbox">
				<tbody>
					<%= for m <- @messages do %>
					<tr class="timestamp">
						<td class=""><%= show_time(m.when) %></td>
						<td class="nickname" style="color: #<%= @color_map[m.from] %>;"><a href="<%= ~p"/user/#{m.from}" %>"><%= m.from %></a></td>
						<td class="message"><%= m.content %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

<!-- Widgets -->
<div class="row">
	<!-- Karma Top 10 -->
	<div class="col-lg-3">
		<div class="widget">
			<div class="">
				<div class="card-body">
					<h5 class="card-title text-center">Karma Top 10</h5>
					<ul class="list-group">
					<%= for k <- @karma_top_10 do %>
					<li class="d-flex justify-content-between align-items-center">
					<%= k.subject %>
					<span class="badge bg-primary badge-pill"><%= k.karma %></span>
					</li>
					<% end %>
					</ul>
				</div><!-- card body -->
			</div><!-- card -->
		</div> <!-- widget -->
	</div> <!-- col -->
	<!-- Karma Bottom 10 -->
	<div class="col-lg-3">
		<div class="widget">
			<div class="">
				<div class="card-body">
					<h5 class="card-title text-center">Karma Bottom 10</h5>
					<ul class="list-group">
					<%= for k <- @karma_bottom_10 do %>
					<li class="d-flex justify-content-between align-items-center">
					<%= k.subject %>
					<span class="badge bg-danger badge-pill"><%= k.karma %></span>
					</li>
					<% end %>
					</ul>
				</div><!-- card body -->
			</div> <!-- card -->
		</div> <!-- widget -->
	</div><!-- col -->
	<!-- Karma Bottom 10 -->
	<div class="col-lg-3">
		<div class="widget">
			<div class="">
				<div class="card-body">
					<h5 class="card-title text-center">Latest URLs</h5>
					<ul class="list-group">
					<%= for u <- @urls do %>
					<li class="d-flex justify-content-between align-items-center">
					<span class="url">
					<a href="<%= raw(u.url) %>">
					<%= u.url %>
					</a>
					</span>
					</li>
					<% end %>
					</ul>
				</div><!-- card body -->
			</div><!-- card -->
		</div><!-- widget -->
	</div><!-- col -->
	<!-- Most Active USers -->
	<div class="col-lg-3">
		<div class="widget">
			<div class="">
				<div class="card-body">
					<h5 class="card-title text-center">Most Active</h5>
					<ul class="list-group">
					<%= for [u, c] <- @most_active do %>
					<li class="d-flex justify-content-between align-items-center">
					<%= u %>
					<span class="badge bg-info badge-pill"><%= c %></span>
					</li>
					<% end %>
					</ul>
				</div><!-- card body -->
			</div><!-- card -->
		</div><!-- widget -->
	</div><!-- col -->
</div>


<!-- Activity Chart -->
<div class="row" phx-update="ignore">
  <div class="col-lg-6 h-100">
    <div class="widget">
      <canvas id="dailyChart"></canvas>
    </div>
  </div>
  <div class="col-lg-6 h-100">
    <div class="widget">
      <canvas id="hourlyChart"></canvas>
    </div>
  </div>
</div>

<script>
  var dailyData = {
      labels: JSON.parse(document.getElementById("daytotals").dataset.labels),
      datasets: [{
          label: 'Messages',
          backgroundColor: "rgb(139, 139, 255)",
          borderColor: "black",
          borderWidth: 0,
          data: JSON.parse(document.getElementById("daytotals").dataset.values)
      }]
  };

  var hourlyData = {
      labels: JSON.parse(document.getElementById("hourtotals").dataset.labels),
      datasets: [{
          label: 'Messages',
          backgroundColor: "rgb(139, 139, 255)",
          borderColor: "black",
          borderWidth: 1,
          data: JSON.parse(document.getElementById("hourtotals").dataset.values)
      }]
  };


  window.onload = function() {
      // Daily chart
      var ctx = document.getElementById('dailyChart').getContext('2d');
      window.myBar = new Chart(ctx, {
          type: 'line',
          data: dailyData,
          filled: true,
          options: {
              elements: {
                  point: {
                     // radius: 1
					  bordercolor: "#8b8bff"
                  }
              },
              legend: {
                  display: true
              },
              responsive: true,
              scales: {
                  xAxes: [{
					  					  ticks: {
						                autoSkip: true,
              maxRotation: 0,
              minRotation: 0
					  },
                      display: true,
                      scaleLabel: {
                          display: true,
                          labelString: 'Date'
                      },
                      gridLines: {
                          display: false
                      }
                  }],
                  yAxes: [{
                      ticks: {
                          precision: 0,
                          beginAtZero: true
                      },
                      gridLines: {
                          display: false
                      },
                      display: true,
                      scaleLabel: {
                          display: true,
                          labelString: '# of Messages'
                      },
                  }]
              }
          }
      });

      // Hourly chart
      var ctx = document.getElementById('hourlyChart').getContext('2d');
      window.myBar = new Chart(ctx, {
          type: 'line',
          filled: false,
          data: hourlyData,
          options: {
              elements: {
                  point: {
                      //radius: 0
					  bordercolor: "#8b8bff"
                  }
              },
              legend: {
                  display: false
              },
              responsive: true,
              scales: {
                  xAxes: [{
					  ticks: {
						                autoSkip: true,
              maxRotation: 0,
              minRotation: 0
					  },
                      display: true,
                      scaleLabel: {
                          display: true,
                          labelString: 'Hour of Day'
                      },
                      gridLines: {
                          display: false
                      }
                  }],
                  yAxes: [{
                      ticks: {
                          precision: 0,
                          beginAtZero: true
                      },
                      gridLines: {
                          display: false
                      },
                      display: true,
                      scaleLabel: {
                          display: true,
                          labelString: '# of Messages'
                      },
                  }]
              }
          }
      });

  };
</script>

lib/ircois_web/live/search_live.html.heex
<div class="row">
	<div class="col-lg-12">
		<form phx-change="search" class="search-form">
			<!-- <.input :grep_field, :query, placeholder: "Pattern to search for", autofocus: true, "phx-debounce": "300", class: "form-control", autocomplete: "off" /> -->
			<input class="form-control" type="text" name="query">
		</form>
	</div>
</div>

<!-- chatbox -->
<div class="row">
	<div class="col-lg-12 mt-4">
		<div class="widget">
			<table class="table chatbox">
				<tbody>
					<%= for m <- @messages do %>
					<tr >
						<td class="timestamp"><%= show_time(m.when) %></td>
						<td class="nickname" style={"color: ##{@color_map[m.from]};"}><a href={~p"/user/#{m.from}"}><%= m.from %></a></td>
						<td class="message" style="width: 78%;"><%= m.content %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

lib/ircois_web/live/search_live.html.leex
<div class="row">
	<div class="col-lg-12">
		<form phx-change="search" class="search-form">
			<%= text_input :grep_field, :query, placeholder: "Pattern to search for", autofocus: true, "phx-debounce": "300", class: "form-control", autocomplete: "off" %>
		</form>
	</div>
</div>

<!-- chatbox -->
<div class="row">
	<div class="col-lg-12 mt-4">
		<div class="widget">
			<table class="table chatbox">
				<tbody>
					<%= for m <- @messages do %>
					<tr >
						<td class="timestamp"><%= show_time(m.when) %></td>
						<td class="nickname" style="color: #<%= @color_map[m.from] %>;"><a href="<%= Routes.user_path(@socket, :user, m.from) %>"><%= m.from %></a></td>
						<td class="message" style="width: 78%;"><%= m.content %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>